FROM hashicorp/vault:1.6.2

RUN wget https://github.com/heronimus/ct-plugin-string2files/releases/download/v0.1.1/string2files-v0.1.1-linux-amd64-musl-debug
RUN chmod +x string2files-v0.1.1-linux-amd64-musl-debug
RUN mv string2files-v0.1.1-linux-amd64-musl-debug /usr/local/bin/string2files

